/**
 * Regenerates everything derived from code: references/commands.md and
 * references/recipes.md, the starter templates, and the preset data assets.
 * Output is deterministic. CI rebuilds and diffs it, so the published skill
 * can never drift from the registries it documents.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { PLATFORM_PRESETS } from '@mcut/cli'
import { CAPTION_STYLE_PRESETS, listToolDefinitions } from '@mcut/timeline'
import { RECIPES } from './recipes'
import { TEMPLATES } from './templates'

const ROOT = join(import.meta.dir, '..')

const GENERATED = '<!-- Generated by tools/generate.ts. Edit the source, not this file. -->'

async function write(relative: string, content: string): Promise<void> {
  const path = join(ROOT, relative)
  await mkdir(join(path, '..'), { recursive: true })
  await writeFile(path, content, 'utf8')
  console.log(`wrote ${relative}`)
}

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`

function rewriteColonConnectors(text: string): string {
  let depth = 0
  let result = ''
  for (let i = 0; i < text.length; i++) {
    const ch = text[i]!
    if (ch === '{') depth += 1
    else if (ch === '}') depth = Math.max(0, depth - 1)
    if (
      depth === 0 &&
      ch === ':' &&
      i > 0 &&
      /\w/.test(text[i - 1]!) &&
      text[i + 1] === ' ' &&
      i + 2 < text.length &&
      /[a-z]/.test(text[i + 2]!)
    ) {
      result += `. ${text[i + 2]!.toUpperCase()}`
      i += 2
      continue
    }
    result += ch
  }
  return result
}

function plainProse(text: string): string {
  const withoutEn = text.replace(/\u2013/g, '-')
  const withoutEm = withoutEn.replace(/\s*\u2014\s*([A-Za-z])?/g, (_m, letter: string | undefined) =>
    letter ? `. ${letter.toUpperCase()}` : '.',
  )
  return rewriteColonConnectors(withoutEm)
}

function mapStringFields<T>(value: T, keys: Set<string>): T {
  if (Array.isArray(value)) return value.map((item) => mapStringFields(item, keys)) as T
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {}
    for (const [key, inner] of Object.entries(value as Record<string, unknown>)) {
      out[key] =
        keys.has(key) && typeof inner === 'string' ? plainProse(inner) : mapStringFields(inner, keys)
    }
    return out as T
  }
  return value
}

const EXCLUDED_COMMANDS = new Set([
  'applyThumbnail',
])

function typeLabel(schema: unknown): string {
  if (typeof schema !== 'object' || schema === null) return 'any'
  const s = schema as Record<string, unknown>
  if (Array.isArray(s.enum)) {
    const label = s.enum.map((v) => JSON.stringify(v)).join(' | ')
    return label.length > 64 ? 'enum' : label
  }
  if (s.const !== undefined) return JSON.stringify(s.const)
  if (s.type === 'array') return `${typeLabel(s.items)}[]`
  if (Array.isArray(s.anyOf)) {
    const label = (s.anyOf as unknown[]).map(typeLabel).join(' | ')
    return label.length > 64 ? 'object' : label
  }
  if (typeof s.type === 'string') return s.type
  return 'object'
}

function commandsMarkdown(): string {
  const tools = listToolDefinitions().filter((tool) => !EXCLUDED_COMMANDS.has(tool.name))
  const lines: string[] = [
    '# Command reference',
    '',
    GENERATED,
    '',
    `Every edit is one of these ${tools.length} serializable commands, dispatched through`,
    '`engine.dispatch({ type, ...payload })`, `mcut apply`, or the matching MCP tool.',
    'Payloads are zod-validated. Invalid commands throw without changing the project.',
    'For a full JSON schema: `mcut commands --name <command>`.',
    '',
  ]
  for (const tool of tools) {
    lines.push(`## ${tool.name}`, '', plainProse(tool.description), '')
    const schema = tool.inputSchema as {
      properties?: Record<string, { description?: string }>
      required?: string[]
    }
    const properties = schema.properties ?? {}
    const required = new Set(schema.required ?? [])
    const names = Object.keys(properties)
    if (names.length > 0) {
      for (const name of names) {
        const property = properties[name]!
        const requiredness = required.has(name) ? 'required' : 'optional'
        const description = property.description ? `: ${plainProse(property.description)}` : ''
        lines.push(`- \`${name}\` (${typeLabel(property)}, ${requiredness})${description}`)
      }
      lines.push('')
    }
  }
  return `${lines.join('\n').trimEnd()}\n`
}

function recipesMarkdown(): string {
  const lines: string[] = [
    '# Recipes',
    '',
    GENERATED,
    '',
    'Each recipe is replayed against its starter template by `recipes.test.ts` in CI.',
    'These command sequences are tested code, not prose. Ids (`e-camera`, `t-default`, ...)',
    'reference the templates in `assets/templates/`. Swap in your own ids.',
    '',
  ]
  for (const recipe of RECIPES) {
    lines.push(`## ${recipe.title}`, '')
    lines.push(`**When the user says:** ${recipe.intent}`)
    lines.push(`**Template:** \`${recipe.template}\``, '')
    lines.push(plainProse(recipe.notes), '')
    if (recipe.commands) {
      lines.push('```json', JSON.stringify(recipe.commands, null, 2), '```', '')
    }
    if (recipe.cli) {
      lines.push(recipe.commands ? 'CLI equivalent:' : 'Use the CLI:', '')
      lines.push('```sh', recipe.cli, '```', '')
    }
  }
  return `${lines.join('\n').trimEnd()}\n`
}

await write('references/commands.md', commandsMarkdown())
await write('references/recipes.md', recipesMarkdown())
await write('assets/platform-presets.json', json(mapStringFields(PLATFORM_PRESETS, new Set(['notes']))))
await write('assets/caption-styles.json', json(CAPTION_STYLE_PRESETS))
for (const template of TEMPLATES) {
  await write(`assets/templates/${template.id}.json`, json(template.build()))
}
