export {
  EditorOperatorRegistry,
  OperatorError,
  createEditorOperatorRegistry,
  emptyInputSchema,
  type EditorOperator,
  type EditorOperatorContext,
  type EnabledResult,
  type ListedEditorOperator,
  type OperatorCategory,
} from './operators'

export {
  addTextAtPlayhead,
  allElementIds,
  clipEdges,
  createSequentialVideoCollage,
  duplicateElement,
  duplicateSelection,
  elementForAsset,
  elementForTextPreset,
  fitCanvasToVideoCollage,
  insertElementAtPlayhead,
  insertElementOnNewTrack,
  insertElementOnTrack,
  isSoloTrack,
  keyframeTimes,
  moveKeyframesAtTime,
  removeKeyframesAtTime,
  removeSelection,
  retimeSequentialCollage,
  selectTrackElements,
  shuttle,
  splitAllAtPlayhead,
  splitSelectionAtPlayhead,
  toggleMasterKeyframe,
  toggleSoloTrack,
  trackOfSelection,
  trimSelectionToPlayhead,
  unlinkElements,
  TEXT_PRESETS,
  type SequentialCollageLayout,
  type SequentialVideoCollageOptions,
  type SequentialVideoCollageResult,
  type TextPreset,
} from './timeline-operators'

export {
  canPlaceIgnoring,
  collectClipDragBases,
  computeSlipRange,
  planAutoCrossfade,
  planDuplicateClipsToNewTracks,
  resolveToolMode,
  type AutoCrossfadePlanInput,
  type ClipDragBase,
  type ClipDragMode,
  type DuplicateClipsToNewTracksOptions,
  type DuplicateClipsToNewTracksPlan,
  type ResolvedClipDragMode,
} from './timeline-gesture'

export {
  planSilenceCuts,
  type SilenceCutOptions,
  type SilenceCutPlan,
  type SilenceCutTranscript,
  type SilenceWindow,
} from './silence-cuts'

export { registerCoreOperators } from './core-operators'
